### ISSUE TITLE
Crash Freezes the player - 1.18.2 - weather2-1.18.2-2.7.5 / ColdSweat-2.2-b04h

### ISSUE THREAD

**Issue by Chassx2** [Momo-Studios/Cold-Sweat-Rework-Forge#134]
Posted this on Weather2's git. 

https://github.com/Corosauce/weather2/issues/582

Soon as the Weather2 storms come it crashes. 

Stacktrace:
	at dev.momostudios.coldsweat.util.compat.CompatManager.isWeather2RainingAt(CompatManager.java:132) ~[ColdSweat-2.2-b04h.jar%23197!/:2.2-b04h] {re:mixin,re:classloading}
	at dev.momostudios.coldsweat.util.world.WorldHelper.isRainingAt(WorldHelper.java:238) ~[ColdSweat-2.2-b04h.jar%23197!/:2.2-b04h] {re:classloading}
	at dev.momostudios.coldsweat.api.temperature.modifier.WaterTempModifier.calculate(WaterTempModifier.java:33) ~[ColdSweat-2.2-b04h.jar%23197!/:2.2-b04h] {re:classloading}
	at dev.momostudios.coldsweat.api.temperature.modifier.TempModifier.update(TempModifier.java:70) ~[ColdSweat-2.2-b04h.jar%23197!/:2.2-b04h] {re:classloading}
	at dev.momostudios.coldsweat.api.util.Temperature.apply(Temperature.java:82) ~[ColdSweat-2.2-b04h.jar%23197!/:2.2-b04h] {re:classloading}
	at dev.momostudios.coldsweat.api.util.Temperature.apply(Temperature.java:95) ~[ColdSweat-2.2-b04h.jar%23197!/:2.2-b04h] {re:classloading}
	at dev.momostudios.coldsweat.common.capability.PlayerTempCap.tickDummy(PlayerTempCap.java:107) ~[ColdSweat-2.2-b04h.jar%23197!/:2.2-b04h] {re:classloading}
	at dev.momostudios.coldsweat.common.event.EntityTempHandler.lambda$onLivingTick$2(EntityTempHandler.java:141) ~[ColdSweat-2.2-b04h.jar%23197!/:2.2-b04h] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.18.2-40.2.9-universal.jar%23766!/:?] {re:mixin,re:classloading}
	at dev.momostudios.coldsweat.common.event.EntityTempHandler.onLivingTick(EntityTempHandler.java:133) ~[ColdSweat-2.2-b04h.jar%23197!/:2.2-b04h] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_3240_EntityTempHandler_onLivingTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:324) ~[forge-1.18.2-40.2.9-universal.jar%23766!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2214) ~[client-1.18.2-20220404.173914-srg.jar%23761!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-

**Comment by MikulDev** [comment]
I've fixed this issue now. Check the issue on the Weather2 repository for more information
