### ISSUE TITLE
[1.18.2&ColdSweat-2.2-b04j] Incompatiable with AdvancedCompass?

### ISSUE THREAD

**Issue by Rocketcat19** [Momo-Studios/Cold-Sweat-Rework-Forge#142]
**Describe the bug**

Freezes when creating a world.But if I removed AdvancedCompass,the world can be loaded correctly.Not sure if its a problem with this mod.

**Additional context**

a part of logs when creating the world

[Server thread/ERROR]: Error executing task on Chunk source main thread executor for minecraft:overworld
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "dev.momostudios.coldsweat.api.temperature.modifier.TempModifier.tickRate(int)" because the return value of "dev.momostudios.coldsweat.api.registry.TempModifierRegistry.getEntryFor(String)" is null
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:198) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:542) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:163) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:550) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:266) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:787) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:176) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:475) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.momostudios.coldsweat.api.temperature.modifier.TempModifier.tickRate(int)" because the return value of "dev.momostudios.coldsweat.api.registry.TempModifierRegistry.getEntryFor(String)" is null
	at dev.momostudios.coldsweat.common.event.EntityTempHandler.lambda$initModifiersOnEntity$11(EntityTempHandler.java:261) ~[ColdSweat-2.2-b04j.jar%2371!/:2.2-b04j]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at dev.momostudios.coldsweat.common.event.EntityTempHandler.initModifiersOnEntity(EntityTempHandler.java:253) ~[ColdSweat-2.2-b04j.jar%2371!/:2.2-b04j]
	at net.minecraftforge.eventbus.ASMEventHandler_681_EntityTempHandler_initModifiersOnEntity_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:80) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157604_(PersistentEntitySectionManager.java:122) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.entity.EntityType$1.m_147060_(EntityType.java:530) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at net.minecraft.world.entity.EntityType.m_20645_(EntityType.java:508) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.entity.EntityType$1.m_147056_(EntityType.java:529) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:?]
	at net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.util.Spliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157559_(PersistentEntitySectionManager.java:121) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerLevel.m_143327_(ServerLevel.java:1507) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ChunkMap.m_143064_(ChunkMap.java:786) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$27(ChunkMap.java:807) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:417) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$29(ChunkMap.java:815) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$30(ChunkMap.java:796) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	... 18 more

[Worker-Main-1/ERROR]: Caught exception in thread Thread[Worker-Main-1,10,main]
java.lang.NullPointerException: Cannot invoke "dev.momostudios.coldsweat.api.temperature.modifier.TempModifier.tickRate(int)" because the return value of "dev.momostudios.coldsweat.api.registry.TempModifierRegistry.getEntryFor(String)" is null
	at dev.momostudios.coldsweat.common.event.EntityTempHandler.lambda$initModifiersOnEntity$11(EntityTempHandler.java:261) ~[ColdSweat-2.2-b04j.jar%2371!/:2.2-b04j]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at dev.momostudios.coldsweat.common.event.EntityTempHandler.initModifiersOnEntity(EntityTempHandler.java:253) ~[ColdSweat-2.2-b04j.jar%2371!/:2.2-b04j]
	at net.minecraftforge.eventbus.ASMEventHandler_681_EntityTempHandler_initModifiersOnEntity_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:80) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157604_(PersistentEntitySectionManager.java:122) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.entity.EntityType$1.m_147060_(EntityType.java:530) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at net.minecraft.world.entity.EntityType.m_20645_(EntityType.java:508) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.entity.EntityType$1.m_147056_(EntityType.java:529) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[?:?]
	at net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.util.Spliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157559_(PersistentEntitySectionManager.java:121) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerLevel.m_143327_(ServerLevel.java:1507) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ChunkMap.m_143064_(ChunkMap.java:786) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$27(ChunkMap.java:807) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:417) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$29(ChunkMap.java:815) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-4.1.27.jar%2334!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$protoChunkToFullChunk$30(ChunkMap.java:796) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:198) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:542) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:163) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:550) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:266) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:787) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:176) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:475) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23148!/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by MikulDev** [comment]
I think this is an issue with the order in which things are loaded in Cold Sweat. Entities seem to load in before the world is finished loading, which I did not realize, and some important Cold Sweat things haven't loaded yet, which causes the error. For the moment, if you want to resolve this issue, you're going to have to remove Serene Seasons (and Weather2 if you have it). This should be fixed in the next update.
