### ISSUE TITLE
Null Point Exception

### ISSUE THREAD

**Issue by DeltaWolf7** [Momo-Studios/Cold-Sweat-Rework-Forge#22]
Hi,

On the latest version r2.1.1 when entering a village on a dedicated server, the client crashes with the below expectation.

java.lang.NullPointerException: Ticking block entity
	at net.momostudios.coldsweat.core.util.WorldInfo.canSeeSky(WorldInfo.java:86) ~[?:r2.1.1] {re:classloading}
	at net.momostudios.coldsweat.common.te.HearthTileEntity.func_73660_a(HearthTileEntity.java:165) ~[?:r2.1.1] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] 

I am trying to gather more info, but have not been able to get close enough to fully figure it out yet.
I will post more if, I can get it. The full log can be viewed here: https://drive.google.com/file/d/1-gYZ-e6-3b6xv8OlKb5YnVgUMmHuIzsC/view?usp=sharing

**Comment by iMikul** [comment]
Thank you for your report. This issue has already been fixed internally and will be part of the next update (2.1.2).
