### ISSUE TITLE
[1.20.1] Error on server startup but no crash

### ISSUE THREAD

**Issue by xhatz** [Momo-Studios/Cold-Sweat-Rework-Forge#234]
Hello! Just wanted to report an error that happens after the world loading on a server, but apparently it does not really affect anything as it does not crash:

`[14Mar2024 13:23:07.478] [Server thread/ERROR] [Cold Sweat/]: Failed to register TempModifier by class name: "com.momosoftworks.coldsweat.api.temperature.modifier.compat.StormTempModifier"!
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.momosoftworks.coldsweat.api.temperature.modifier.compat.StormTempModifier
	at com.momosoftworks.coldsweat.api.event.core.TempModifierRegisterEvent.lambda$registerByClassName$0(TempModifierRegisterEvent.java:37) ~[ColdSweat-2.3-b02b.jar%23219!/:2.3-b02b]
	at com.momosoftworks.coldsweat.api.registry.TempModifierRegistry.register(TempModifierRegistry.java:22) ~[ColdSweat-2.3-b02b.jar%23219!/:2.3-b02b]
	at com.momosoftworks.coldsweat.api.event.core.TempModifierRegisterEvent.register(TempModifierRegisterEvent.java:27) ~[ColdSweat-2.3-b02b.jar%23219!/:2.3-b02b]
	at com.momosoftworks.coldsweat.api.event.core.TempModifierRegisterEvent.registerByClassName(TempModifierRegisterEvent.java:34) ~[ColdSweat-2.3-b02b.jar%23219!/:2.3-b02b]
	at com.momosoftworks.coldsweat.core.init.TempModifierInit.registerTempModifiers(TempModifierInit.java:190) ~[ColdSweat-2.3-b02b.jar%23219!/:2.3-b02b]
	at com.momosoftworks.coldsweat.core.init.__TempModifierInit_registerTempModifiers_TempModifierRegisterEvent.invoke(.dynamic) ~[ColdSweat-2.3-b02b.jar%23219!/:2.3-b02b]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at com.momosoftworks.coldsweat.core.init.TempModifierInit.buildRegistries(TempModifierInit.java:44) ~[ColdSweat-2.3-b02b.jar%23219!/:2.3-b02b]
	at com.momosoftworks.coldsweat.core.init.TempModifierInit.onServerStart(TempModifierInit.java:35) ~[ColdSweat-2.3-b02b.jar%23219!/:2.3-b02b]
	at com.momosoftworks.coldsweat.core.init.__TempModifierInit_onServerStart_ServerStartingEvent.invoke(.dynamic) ~[ColdSweat-2.3-b02b.jar%23219!/:2.3-b02b]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:110) ~[forge-1.20.1-47.2.20-universal.jar%23306!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:201) ~[server-1.20.1-20230612.114412-srg.jar%23301!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[server-1.20.1-20230612.114412-srg.jar%23301!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23301!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.momosoftworks.coldsweat.api.temperature.modifier.compat.StormTempModifier
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at com.momosoftworks.coldsweat.api.event.core.TempModifierRegisterEvent.lambda$registerByClassName$0(TempModifierRegisterEvent.java:36) ~[ColdSweat-2.3-b02b.jar%23219!/:2.3-b02b]
	... 19 more`

Edit: I think it happens because of the mod Weather, Storms & Tornadoes.

**Comment by MikulDev** [comment]
Thanks for letting me know. This will be fixed in the next version
