### ISSUE TITLE
Curious Chameleon Crash

### ISSUE THREAD

**Issue by sillypickly45** [Momo-Studios/Cold-Sweat-Rework-Forge#237]
Whenever I load into a chunk with a chameleon in it, or a chameleon spawns in a loaded chunk, the game crashes. 

I am using ColdSweat-2.3-b02b.

Here is a crash report:

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Server thread
Suspected Mod: 
	Cold Sweat (cold_sweat), Version: 2.3-b02b
		at TRANSFORMER/cold_sweat@2.3-b02b/com.momosoftworks.coldsweat.util.world.WorldHelper.entityDropItem(WorldHelper.java:388)
Stacktrace:
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:227) ~[fmlcore-1.20.1-47.2.20.jar%23173!/:?] {}
	at com.momosoftworks.coldsweat.util.world.WorldHelper.entityDropItem(WorldHelper.java:388) ~[ColdSweat-2.3-b02b.jar%23166!/:2.3-b02b] {re:classloading}
	at com.momosoftworks.coldsweat.common.entity.Chameleon.m_8119_(Chameleon.java:305) ~[ColdSweat-2.3-b02b.jar%23166!/:2.3-b02b] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: cold_sweat:chameleon (com.momosoftworks.coldsweat.common.entity.Chameleon)
	Entity ID: 316
	Entity Name: Chameleon
	Entity's Exact location: 680.00, 85.00, 474.00
	Entity's Block location: World: (680,85,474), Section: (at 8,5,10 in 42,5,29; chunk contains blocks 672,-64,464 to 687,319,479), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,-64,0 to 1023,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cold_sweat.mixin.json:MixinBlockUpdate,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:124) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
 
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		ColdSweat-2.3-b02b.jar                            |Cold Sweat                    |cold_sweat                    |2.3-b02b            |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.3.9_mc1.20.1.jar           |AmbientSounds                 |ambientsounds                 |5.3.9               |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.20-universal.jar                |Forge                         |forge                         |47.2.20             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		geckolib-forge-1.20.1-4.4.2.jar                   |GeckoLib 4                    |geckolib                      |4.4.2               |DONE      |Manifest: NOSIGNATURE
		the monkey 1.20.1 - 1.2.1b.jar                    |The Man From The Fog          |man                           |1.2.1               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.25_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.25             |DONE      |Manifest: NOSIGNATURE
		From-The-Fog-1.20-v1.9.2-Forge-Fabric.jar         |From The Fog                  |watching                      |1.9.2               |DONE      |Manifest: NOSIGNATURE
		sanitydim-mc1.20-1.1.0.jar                        |Sanity: Descent Into Madness  |sanitydim                     |1.1.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: c155f96a-b927-4649-a2a4-9d14701f5daa

**Comment by MidnightMangled** [comment]
I know I ain't the creator but I believe this has the solution as the issue I had asked about because something I hadn't said in my issue was that the chameleons kept getting killed by a ticking fixer tool I had in my mod-pack at the time.

I would try using the same solution that the creator of the mod told me in my issue-report:
https://github.com/Momo-Softworks/Cold-Sweat/issues/238

**Comment by MikulDev** [comment]
I found the source of the issue. I think it's caused when a chameleon is ready to shed its skin. The action of dropping the chameleon molt item causes the crash.
