### ISSUE TITLE
SERVER CRASH

### ISSUE THREAD

**Issue by Magmine123** [Momo-Studios/Cold-Sweat-Rework-Forge#253]
I am playing on 1.19.2. My game has been constantly crashing because of Cold Sweat. Here is the log. i don't know if ive done this right but we will see.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-03-31 14:14:55
Description: Rendering overlay

net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file coldsweat/world_settings.toml of type COMMON for modid cold_sweat
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:68) ~[forge-1.19.2-43.3.0-universal.jar%23268!/:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$23(ModLoader.java:207) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:207) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$loadMods$17(ModLoader.java:191) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:191) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$startModLoading$5(ClientModLoader.java:120) ~[forge-1.19.2-43.3.0-universal.jar%23268!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111) ~[forge-1.19.2-43.3.0-universal.jar%23268!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.startModLoading(ClientModLoader.java:120) ~[forge-1.19.2-43.3.0-universal.jar%23268!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:102) ~[forge-1.19.2-43.3.0-universal.jar%23268!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111) ~[forge-1.19.2-43.3.0-universal.jar%23268!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid character ':' after key [inecraft]
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:152) ~[toml-3.6.4.jar%2391!/:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.4.jar%2391!/:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:88) ~[toml-3.6.4.jar%2391!/:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.4.jar%2391!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.4.jar%2390!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.4.jar%2390!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.4.jar%2390!/:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.4.jar%2390!/:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.4.jar%2390!/:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:43) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.19.2-43.3.0.jar%23264!/:?] {}
	at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:68) ~[forge-1.19.2-43.3.0-universal.jar%23268!/:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1295) ~[client-1.19.2-20220805.130853-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:justzoom.mixin.json:MixinGameRenderer,pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin,pl:mixin:APP:mixins.essential.json:events.Mixin_GuiDrawScreenEvent_Priority,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:weeping_angels-common.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:cold_sweat.mixin.json:MixinInventoryOpenClient,pl:mixin:APP:mixins.essential.json:client.Mixin_RunEssentialTasks,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.vanilla.Mixin_WorkaroundBrokenFramebufferBlitBlending,pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23263!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:weeping_angels-common.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:cold_sweat.mixin.json:MixinInventoryOpenClient,pl:mixin:APP:mixins.essential.json:client.Mixin_RunEssentialTasks,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.vanilla.Mixin_WorkaroundBrokenFramebufferBlitBlending,pl:mixin:APP:mixins.essential.json:events.Mixin_RenderTickEvent,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23263!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23263!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.0.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Mod Resources, Essential (forge_1.19.2).jar

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1169067952 bytes (1114 MiB) / 1946157056 bytes (1856 MiB) up to 8388608000 bytes (8000 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5176
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25518.35
	Virtual memory used (MB): 15305.61
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 27.75
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8000m -Xms256m
	Launched Version: forge-43.3.0
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.76, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.19.2_HD_U_I2
	OptiFine Build: 20230623-171717
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryUnbound_r5.1.1.zip
	OpenGlVersion: 3.2.0 NVIDIA 551.76
	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.3.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.3.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.3.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar essential-loader TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
		kotlinforforge@3.6.0
	Mod List: 
		Weeping-Angels-43.0.9-forge.jar                   |Weeping Angels                |weeping_angels                |43.0.9              |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1019.jar                  |Just Enough Items             |jei                           |11.6.0.1019         |COMMON_SET|Manifest: NOSIGNATURE
		The_Graveyard_2.5.3_(FORGE)_for_1.19.2..jar       |The Graveyard                 |graveyard                     |2.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		music_player-1.19.2-2.5.1.233.jar                 |Music Player                  |musicplayer                   |2.5.1.233           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		vanilla-refresh-1.4.17c.jar                       |Vanilla Refresh               |mr_vanilla_refresh            |1.4.17c             |COMMON_SET|Manifest: NOSIGNATURE
		Nightmare 1.19.2.jar                              |Dweller                       |dweller                       |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.1.4-1.19.jar                            |Citadel                       |citadel                       |2.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |COMMON_SET|Manifest: NOSIGNATURE
		travelersbackpack-forge-1.19.2-8.2.39.jar         |Traveler's Backpack           |travelersbackpack             |8.2.39              |COMMON_SET|Manifest: NOSIGNATURE
		Horror_elements_mod_1.5.6_1.19.2.jar              |Horror Element Mod            |horror_element_mod            |1.5.6               |COMMON_SET|Manifest: NOSIGNATURE
		SereneSeasons-1.19.2-8.1.0.24.jar                 |Serene Seasons                |sereneseasons                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		deepslatetweaks-1.2-1.19.2.jar                    |Deepslate Tweaks              |deepslatetweaks               |1.2                 |COMMON_SET|Manifest: NOSIGNATURE
		u_team_core-forge-1.19.2-4.4.3.287.jar            |U Team Core                   |uteamcore                     |4.4.3.287           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		cloth-config-8.3.115-forge.jar                    |Cloth Config v8 API           |cloth_config                  |8.3.115             |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.3.0-universal.jar                 |Forge                         |forge                         |43.3.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		SpelunkersCharm-3.5.9-1.19.2.jar                  |Spelunker's Charm             |spelunkers_charm              |3.5.9               |COMMON_SET|Manifest: NOSIGNATURE
		twilightforest-1.19.2-4.2.1518-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1518            |COMMON_SET|Manifest: NOSIGNATURE
		konkrete_forge_1.8.0_MC_1.19-1.19.2.jar           |Konkrete                      |konkrete                      |1.8.0               |COMMON_SET|Manifest: NOSIGNATURE
		MoreArmor1.4.2.jar                                |More Armor                    |morearmor                     |1.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		TheOneWhoWatches-V1.3.0-1.19.2.jar                |The One Who Watches           |the_one_who_watches           |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		DynamicSurroundings-6.0.0.2.jar                   |§3Dynamic Surroundings: Resurr|dsurround                     |6.0.0.2             |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		sons-of-sins-1.19.2-2.1.6.jar                     |Sons of Sins                  |sons_of_sins                  |2.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		voicechat-forge-1.19.2-2.5.11.jar                 |Simple Voice Chat             |voicechat                     |1.19.2-2.5.11       |COMMON_SET|Manifest: NOSIGNATURE
		sound-physics-remastered-forge-1.19.2-1.3.1.jar   |Sound Physics Remastered      |sound_physics_remastered      |1.19.2-1.3.1        |COMMON_SET|Manifest: NOSIGNATURE
		the_midnight_lurker_3.0.10.jar                    |The Midnight Lurker           |midnightlurker                |3.0.10              |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.2-2.0.1.136.jar           |TerraBlender                  |terrablender                  |2.0.1.136           |COMMON_SET|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.13_mc1.19.2.jar          |Ambient Sounds                |ambientsounds                 |5.2.13              |COMMON_SET|Manifest: NOSIGNATURE
		RegionsUnexploredForge-0.5.3+1.19.2.jar           |Regions Unexplored            |regions_unexplored            |0.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.2-17.1.1.162.jar               |Biomes O' Plenty              |biomesoplenty                 |17.1.1.162          |COMMON_SET|Manifest: NOSIGNATURE
		vtaw_mw-forge-1.19-41.0.100-1.0.2.jar             |Variant Tools and Weaponry - E|vtaw_mw                       |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.9.4_mc1.19.2.jar            |CreativeCore                  |creativecore                  |2.9.3               |COMMON_SET|Manifest: NOSIGNATURE
		From-The-Fog-1.19-v1.9.1-Forge-Fabric.jar         |From The Fog                  |watching                      |1.9.1               |COMMON_SET|Manifest: NOSIGNATURE
		EyesInTheDarkness-1.19.2-1.3.10.jar               |Eyes in the Darkness          |eyesinthedarkness             |1.3.10              |COMMON_SET|Manifest: NOSIGNATURE
		whisperwoods-1.19-2.1.1-forge.jar                 |Whisperwoods                  |whisperwoods                  |1.19-2.1.1          |COMMON_SET|Manifest: NOSIGNATURE
		The-Man-From-The-Fog-1.2.3-1.19.2.jar             |The Man From The Fog          |man                           |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		[1.19.2] SecurityCraft v1.9.6.1.jar               |SecurityCraft                 |securitycraft                 |1.9.6.1             |COMMON_SET|Manifest: NOSIGNATURE
		Slenderman1.2.jar                                 |Slenderman                    |slenderman                    |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Apollyon v1.0.0 (1.19.2).jar                      |Apollyon                      |apollyon                      |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		fogoverrides-1.19.2-1.2.1.jar                     |Fog Overrides                 |fogoverrides                  |1.19.2-1.2.1        |COMMON_SET|Manifest: NOSIGNATURE
		endofherobrine-1.19.2-1.0.8.2.jar                 |The End of Herobrine          |endofherobrine                |1.19.2-1.0.8.2      |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.6.92-forge.jar                     |Architectury                  |architectury                  |6.6.92              |COMMON_SET|Manifest: NOSIGNATURE
		ColdSweat-2.2.5.1.jar                             |Cold Sweat                    |cold_sweat                    |2.2.5.1             |COMMON_SET|Manifest: NOSIGNATURE
		justzoom_forge_1.0.1-1_MC_1.19.jar                |Just Zoom                     |justzoom                      |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		svmm-1.19.2-1.2.4.0.jar                           |Server-side Vein Miner        |svmm                          |1.19.2-1.19.2-1.2.4.|COMMON_SET|Manifest: NOSIGNATURE
		DynamicTrees-1.19.2-1.2.0-BETA1.jar               |Dynamic Trees                 |dynamictrees                  |1.19.2-1.2.0-BETA1  |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |COMMON_SET|Manifest: NOSIGNATURE
		Cave Dweller Reimagined.jar                       |cave_dweller                  |cave_dweller                  |1.6.4               |COMMON_SET|Manifest: NOSIGNATURE
		WORKING_SKINSTALKER - 1.19.2.jar                  |skinstalker                   |skinstalker                   |1.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		NEWSPAWN_GOATMAN-1.19.2 - By Flamc04.jar          |goatman                       |goatman                       |1.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		THE_CREATION-1.19.2.jar                           |creation                      |creation                      |1.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		Essential (forge_1.19.2).jar                      |Essential                     |essential                     |1.3.1.2+g7ed10f42d2 |COMMON_SET|Manifest: NOSIGNATURE
		xptome-1.19-2.1.7.jar                             |XP Tome                       |xpbook                        |2.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		PresenceFootsteps-1.19.2-1.6.4.1-forge.jar        |Presence Footsteps (Forge)    |presencefootsteps             |1.19.2-1.6.4.1      |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 27e77154-1ab3-4c04-9360-2bf1f2d0f13c
	FML: 43.3
	Forge: net.minecraftforge:43.3.0

**Comment by MikulDev** [comment]
Maybe try deleting the config files? I'm not sure why Forge can't read the configs.

**Comment by Magmine123** [comment]
Thank you so much! this fixed the issue!

**Comment by MikulDev** [comment]
Awesome, no problem.
