### ISSUE TITLE
crash on 1.20.1 when using cardboard boxes from mekanism or cardboard box extension

### ISSUE THREAD

**Issue by Marre0801** [Momo-Studios/Cold-Sweat-Rework-Forge#341]
i made a personal modpack recently using cold sweat and when i used the cardboard box on a chest with items inside of it it worked fine but when i tried removing the box i get this error and the game crashed when i tried using mekanism cardboard box it also crashed but instantly when i click the chest

[Render thread/ERROR]:Unreported exception thrown!
java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.20.1 of loader 'TRANSFORMER' @1e977098)
	at com.momosoftworks.coldsweat.common.event.IceBreakingEvents.onIceBreak(IceBreakingEvents.java:25) ~[ColdSweat-2.3.jar%23172!/:2.3]
	at com.momosoftworks.coldsweat.common.event.__IceBreakingEvents_onIceBreak_BreakEvent.invoke(.dynamic) ~[ColdSweat-2.3.jar%23172!/:2.3]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at mekanism.common.item.block.ItemBlockCardboardBox.canReplace(ItemBlockCardboardBox.java:64) ~[Mekanism-1.20.1-10.4.8.43.jar%23179!/:10.4.8]
	at mekanism.common.item.block.ItemBlockCardboardBox.onItemUseFirst(ItemBlockCardboardBox.java:88) ~[Mekanism-1.20.1-10.4.8.43.jar%23179!/:10.4.8]
	at net.minecraft.world.item.ItemStack.lambda$onItemUseFirst$4(ItemStack.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:261) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.world.item.ItemStack.onItemUseFirst(ItemStack.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:310) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:291) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:290) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1698) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?][16:15:03] [Render thread/ERROR]:Exception caught during firing event: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.20.1 of loader 'TRANSFORMER' @1e977098)
	Index: 2
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$1552/0x0000026e1d6a1338@5eba1893
		2: ASM: class com.momosoftworks.coldsweat.common.event.IceBreakingEvents onIceBreak(Lnet/minecraftforge/event/level/BlockEvent$BreakEvent;)V
		3: ASM: mekanism.common.CommonWorldTickHandler@1ddf61f0 onBlockBreak(Lnet/minecraftforge/event/level/BlockEvent$BreakEvent;)V
java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.20.1 of loader 'TRANSFORMER' @1e977098)
	at TRANSFORMER/cold_sweat@2.3/com.momosoftworks.coldsweat.common.event.IceBreakingEvents.onIceBreak(IceBreakingEvents.java:25)
	at TRANSFORMER/cold_sweat@2.3/com.momosoftworks.coldsweat.common.event.__IceBreakingEvents_onIceBreak_BreakEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/mekanism@10.4.8/mekanism.common.item.block.ItemBlockCardboardBox.canReplace(ItemBlockCardboardBox.java:64)
	at TRANSFORMER/mekanism@10.4.8/mekanism.common.item.block.ItemBlockCardboardBox.onItemUseFirst(ItemBlockCardboardBox.java:88)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.lambda$onItemUseFirst$4(ItemStack.java:250)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:261)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.onItemUseFirst(ItemStack.java:250)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:310)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:291)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:290)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1698)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by Marre0801** [comment]
also im running single player i forgot to say that

**Comment by MikulDev** [comment]
I will have this fixed in the update releasing very soon. Thanks for the report

**Comment by Marre0801** [comment]
you're welcome happy to be of help
