### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RadekWeather** [Momo-Studios/Cold-Sweat-Rework-Forge#35]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 22.03.2022, 19:34
Description: Unexpected error

java.lang.NullPointerException: Registry Object not present: cold_sweat:hearth
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:116) ~[forge-1.18.1-39.0.14-universal.jar%2371!:?] {re:classloading}
	at dev.momostudios.coldsweat.util.registries.ModBlockEntities.get(ModBlockEntities.java:21) ~[ColdSweat-2.1.9.jar%2358!:2.1.9] {re:classloading}
	at dev.momostudios.coldsweat.common.blockentity.HearthBlockEntity.<init>(HearthBlockEntity.java:63) ~[ColdSweat-2.1.9.jar%2358!:2.1.9] {re:classloading}
	at dev.momostudios.coldsweat.common.block.HearthBottomBlock.m_142194_(HearthBottomBlock.java:127) ~[ColdSweat-2.1.9.jar%2358!:2.1.9] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:251) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading}
	at net.minecraft.world.level.Level.m_6933_(Level.java:202) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:cold_sweat.mixin.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.Level.m_7731_(Level.java:179) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:cold_sweat.mixin.json:MixinLevel,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_7731_(ClientLevel.java:633) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:161) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:66) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:213) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:228) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:213) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105262_(MultiPlayerGameMode.java:310) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.m_105262_(PlayerControllerOF.java:96) ~[OptiFine_1.18.1_HD_U_H4.jar%2372!:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1554) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1842) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1651) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.14.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:116) ~[forge-1.18.1-39.0.14-universal.jar%2371!:?] {re:classloading}
	at dev.momostudios.coldsweat.util.registries.ModBlockEntities.get(ModBlockEntities.java:21) ~[ColdSweat-2.1.9.jar%2358!:2.1.9] {re:classloading}
	at dev.momostudios.coldsweat.common.blockentity.HearthBlockEntity.<init>(HearthBlockEntity.java:63) ~[ColdSweat-2.1.9.jar%2358!:2.1.9] {re:classloading}
	at dev.momostudios.coldsweat.common.block.HearthBottomBlock.m_142194_(HearthBottomBlock.java:127) ~[ColdSweat-2.1.9.jar%2358!:2.1.9] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:251) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading}
	at net.minecraft.world.level.Level.m_6933_(Level.java:202) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:cold_sweat.mixin.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.Level.m_7731_(Level.java:179) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:computing_frames,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:cold_sweat.mixin.json:MixinLevel,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_7731_(ClientLevel.java:633) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:161) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:66) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading}
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:213) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:228) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:213) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105262_(MultiPlayerGameMode.java:310) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.m_105262_(PlayerControllerOF.java:96) ~[OptiFine_1.18.1_HD_U_H4.jar%2372!:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1554) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1842) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Radek'/130, l='ClientLevel', x=68.92, y=64.00, z=-34.17]]
	Chunk stats: 961, 591
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,80,0), Section: (at 0,0,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 476 game time, 476 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:517) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2367!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.14.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 928428712 bytes (885 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3,29
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.13023.4001
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 18754,14
	Virtual memory used (MB): 13085,92
	Swap memory total (MB): 2432,00
	Swap memory used (MB): 15,95
	JVM Flags: 14 total; -XX:+UnlockExperimentalVMOptions -XX:-UseParallelGC -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx2048M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Launched Version: 1.18.1-forge-39.0.14
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Radeon RX 580 Series GL version 3.2.14761 Core Profile Forward-Compatible Context 21.30.23.04 30.0.13023.4001, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: Polski (Polska)
	CPU: 8x Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Radek'/130, l='ServerLevel[Pogoda]', x=68.91, y=64.00, z=-34.17]]
	Data Packs: vanilla, mod:sereneseasons (incompatible), mod:configured (incompatible), mod:cold_sweat (incompatible), mod:clear_skies (incompatible), mod:betterfpsdist (incompatible), mod:forge, mod:mctb (incompatible), mod:worldedit, mod:coroutil (incompatible), mod:sound_physics_remastered, mod:jei (incompatible), mod:hungerstrike (incompatible)
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.14761 Core Profile Forward-Compatible Context 21.30.23.04 30.0.13023.4001
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		SereneSeasons-1.18.1-6.0.0.11-universal.jar       |Serene Seasons                |sereneseasons                 |1.18.1-6.0.0.11     |DONE      |Manifest: NOSIGNATURE
		configured-1.5.1-1.18.1.jar                       |Configured                    |configured                    |1.5.1               |DONE      |Manifest: NOSIGNATURE
		ColdSweat-2.1.9.jar                               |Cold Sweat                    |cold_sweat                    |2.1.9               |DONE      |Manifest: NOSIGNATURE
		clear-skies-forge-mc118-2.0.88.jar                |Clear Skies                   |clear_skies                   |2.0.88              |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.18-1.3.jar                        |betterfpsdist mod             |betterfpsdist                 |1.18-1.3            |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.14-universal.jar                |Forge                         |forge                         |39.0.14             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		MoreCraftingTables+1.18.1.jar                     |More Crafting Tables Mod      |mctb                          |1.18.1              |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.8.jar                           |WorldEdit                     |worldedit                     |7.2.8+6008-1246d61  |DONE      |Manifest: NOSIGNATURE
		coroutil-1.18.1-1.2.37.jar                        |CoroUtil                      |coroutil                      |1.18.1-1.2.37       |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.1-1.0.4.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		HungerStrike-1.18-6.0.0.jar                       |Hunger Strike                 |hungerstrike                  |1.18-6.0.0          |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d967d989-946a-40f6-a090-7be9760b883c
	FML: 39.0
	Forge: net.minecraftforge:39.0.14

**Comment by MikulDev** [comment]
Thanks for posing your crash report. I'm working on the issue and it'll be fixed in a patch update soon.
