### ISSUE TITLE
Cold Sweat causes a crash with latest version of Serene Seasons

### ISSUE THREAD

**Issue by Scarlet-Fury** [Momo-Studios/Cold-Sweat-Rework-Forge#384]
Updated Serene Seasons, Cold Sweat crashed the game, here's the crash log:
 
 ---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-10-07 01:59:46
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.11-universal.jar%23187!/:?] {re:mixin,re:classloading,pl:mixin:APP:xenon.mixins.json:core.CrashReportExtenderMixin,pl:mixin:A}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:138) ~[forge-1.20.1-47.3.11-universal.jar%23187!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft,pl:mixin:APP:cold_sweat.mixin.json:MixinInventoryOpenClient,pl:mixin:APP:cold_sweat.mixin.json:MixinPickEntity,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:xenon.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:xenon.mixins.json:core.render.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft,pl:mixin:APP:cold_sweat.mixin.json:MixinInventoryOpenClient,pl:mixin:APP:cold_sweat.mixin.json:MixinPickEntity,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:xenon.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:xenon.mixins.json:core.render.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.3.11-universal.jar%23187!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:xenon.mixins.json:extras.darkness.GameRendererMixin,pl:mixin:APP:xenon.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft,pl:mixin:APP:cold_sweat.mixin.json:MixinInventoryOpenClient,pl:mixin:APP:cold_sweat.mixin.json:MixinPickEntity,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:xenon.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:xenon.mixins.json:core.render.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23182!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft,pl:mixin:APP:cold_sweat.mixin.json:MixinInventoryOpenClient,pl:mixin:APP:cold_sweat.mixin.json:MixinPickEntity,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:xenon.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:xenon.mixins.json:core.render.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.11.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:147) ~[eventbus-6.0.5.jar%2387!/:?] {}
-- MOD cold_sweat --
Details:
	Mod File: /C:/Users/LucasClanCat/curseforge/minecraft/Instances/Wildborne - BETA 6.00+/mods/ColdSweat-2.3.5.jar
	Failure message: Cold Sweat (cold_sweat) has failed to load correctly
		java.lang.IllegalArgumentException: Method public void com.momosoftworks.coldsweat.util.compat.CompatManager$3.onSeasonChange(sereneseasons.api.season.SeasonChangedEvent$Standard) has @SubscribeEvent annotation, but takes an argument that is not an Event subtype : class sereneseasons.api.season.SeasonChangedEvent$Standard
	Mod Version: 2.3.5
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.IllegalArgumentException: Method public void com.momosoftworks.coldsweat.util.compat.CompatManager$3.onSeasonChange(sereneseasons.api.season.SeasonChangedEvent$Standard) has @SubscribeEvent annotation, but takes an argument that is not an Event subtype : class sereneseasons.api.season.SeasonChangedEvent$Standard
Stacktrace:
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:147) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$6(EventBus.java:106) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:106) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:102) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:128) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at com.momosoftworks.coldsweat.util.compat.CompatManager.registerEventHandlers(CompatManager.java:324) ~[ColdSweat-2.3.5.jar%23169!/:2.3.5] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.ColdSweat.<init>(ColdSweat.java:73) ~[ColdSweat-2.3.5.jar%23169!/:2.3.5] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77) ~[javafmllanguage-1.20.1-47.3.11.jar%23184!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.11.jar%23183!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1174078560 bytes (1119 MiB) / 1644167168 bytes (1568 MiB) up to 16810770432 bytes (16032 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: CyberLink Mirror Driver
	Graphics card #0 vendor: CyberLink
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.0.0.0
	Graphics card #1 name: NVIDIA GeForce RTX 3080
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2216
	Graphics card #1 versionInfo: DriverVersion=32.0.15.6094
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 32768.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 32768.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 131792.67
	Virtual memory used (MB): 38327.86
	Swap memory total (MB): 800.00
	Swap memory used (MB): 114.30
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16032m -Xms256m
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		radium-mc1.20.1-0.12.4+git.26c9d8e.jar            |Radium                        |radium                        |0.12.4+git.26c9d8e  |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |COMMON_SET|Manifest: NOSIGNATURE
		ThirstWasTaken-1.20.1-1.3.9.jar                   |Thirst was Taken              |thirst                        |1.20.1-1.3.9        |COMMON_SET|Manifest: NOSIGNATURE
		weather2-1.20.1-2.8.3.jar                         |Weather2                      |weather2                      |1.20.1-2.8.3        |COMMON_SET|Manifest: NOSIGNATURE
		GlitchCore-forge-1.20.1-0.0.1.1.jar               |GlitchCore                    |glitchcore                    |0.0.1.1             |COMMON_SET|Manifest: NOSIGNATURE
		SereneSeasons-forge-1.20.1-9.1.0.0.jar            |Serene Seasons                |sereneseasons                 |9.1.0.0             |COMMON_SET|Manifest: NOSIGNATURE
		sereneseasonsfix-1.20.2-1.1.0.jar                 |Sereneseasons Fix             |sereneseasonsfix              |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		coroutil-forge-1.20.1-1.3.7.jar                   |CoroUtil                      |coroutil                      |1.20.1-1.3.7        |COMMON_SET|Manifest: NOSIGNATURE
		xenon-0.3.31+mc1.20.1.jar                         |Xenon                         |xenon                         |0.3.31              |COMMON_SET|Manifest: NOSIGNATURE
		seasonhud-forge-1.20.1-1.10.9.jar                 |SeasonHUD                     |seasonhud                     |1.10.9              |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		ColdSweat-2.3.5.jar                               |Cold Sweat                    |cold_sweat                    |2.3.5               |ERROR     |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.11-universal.jar                |Forge                         |forge                         |47.3.11             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		gpumemleakfix-1.20.1-1.8.jar                      |Gpu memory leak fix           |gpumemleakfix                 |1.20.1-1.8          |COMMON_SET|Manifest: NOSIGNATURE
		modernfix-forge-5.19.4+mc1.20.1.jar               |ModernFix                     |modernfix                     |5.19.4+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 71be6890-3814-4a24-9929-1ca314662f85
	FML: 47.3
	Forge: net.minecraftforge:47.3.11

**Comment by Scarlet-Fury** [comment]
Here's a screenshot of the specific crash message as well
![image_2024-10-07_021026397](https://github.com/user-attachments/assets/a4ceb814-8d4f-4d76-b332-f5b392e76b1c)

**Comment by FunnelVortex** [comment]
The recent SereneSeasons update is broken, it's literally incompatible with itself. I'd roll back to SereneSeasons 9.0.0.46 until the author of that mod has time to correct it.

**Comment by Sato-Devs** [comment]
> The recent SereneSeasons update is broken, it's literally incompatible with itself. I'd roll back to SereneSeasons 9.0.0.46 until the author of that mod has time to correct it.

why not 9.3?

**Comment by MikulDev** [comment]
I will be closing this issue because the solution has already been found. This will be addressed in the next version.
