### ISSUE TITLE
StackOverflowError crash on boiler 

### ISSUE THREAD

**Issue by Roclh** [Momo-Studios/Cold-Sweat-Rework-Forge#423]
Time: 2024-12-14 22:19:34
Description: Ticking block entity

java.lang.StackOverflowError: Ticking block entity
	at net.minecraft.world.item.ItemStack.m_41720_(ItemStack.java:217) ~[client-1.20.1-20230612.114412-srg.jar%23206!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:mixins.irons_spellbooks.json:ItemStackMixin,pl:mixin:APP:glitchcore.mixins.json:MixinItemStack,pl:mixin:APP:cold_sweat.mixin.json:MixinItemTooltip,pl:mixin:A}
	at com.momosoftworks.coldsweat.util.serialization.ConfigHelper.findFirstFuelMatching(ConfigHelper.java:573) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.BoilerBlockEntity.getItemFuel(BoilerBlockEntity.java:197) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.checkForFuel(HearthBlockEntity.java:611) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.m_6596_(HearthBlockEntity.java:571) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.updateFuelState(HearthBlockEntity.java:896) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.setHotFuel(HearthBlockEntity.java:846) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.BoilerBlockEntity.setHotFuel(BoilerBlockEntity.java:228) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.setHotFuelAndUpdate(HearthBlockEntity.java:850) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.BoilerBlockEntity.addFuel(BoilerBlockEntity.java:234) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.BoilerBlockEntity.storeFuel(BoilerBlockEntity.java:209) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.checkForFuel(HearthBlockEntity.java:614) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.m_6596_(HearthBlockEntity.java:571) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.updateFuelState(HearthBlockEntity.java:896) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
....
	at com.momosoftworks.coldsweat.common.blockentity.BoilerBlockEntity.storeFuel(BoilerBlockEntity.java:209) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.checkForFuel(HearthBlockEntity.java:614) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.m_6596_(HearthBlockEntity.java:571) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.updateFuelState(HearthBlockEntity.java:896) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.HearthBlockEntity.setHotFuel(HearthBlockEntity.java:846) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:mixin,re:classloading}
	at com.momosoftworks.coldsweat.common.blockentity.BoilerBlockEntity.setHotFuel(BoilerBlockEntity.java:228) ~[ColdSweat-2.3.9.jar%23184!/:2.3.9] {re:classloading}------------------------------------------------------------------
```

**Comment by Roclh** [comment]
Can't open the world, crashes on world start

**Comment by MikulDev** [comment]
This is a known issue on 2.3.9. Fixed in 2.3.10
