### ISSUE TITLE
Server Crash 2.1.10.3

### ISSUE THREAD

**Issue by DeltaWolf7** [Momo-Studios/Cold-Sweat-Rework-Forge#89]
Hi,

It looks like a client class is not marked as such to prevent the server from calling it.

Caused by 0: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
		at dev.momostudios.coldsweat.core.network.ColdSweatPacketHandler.init(ColdSweatPacketHandler.java:39) ~[ColdSweat-2.1.10.3.jar%23116!/:2.1.10.3] {re:classloading}
		at dev.momostudios.coldsweat.ColdSweat.commonSetup(ColdSweat.java:63) ~[ColdSweat-2.1.10.3.jar%23116!/:2.1.10.3] {re:classloading}

Sorry

**Comment by Kallixer** [comment]
I'm getting this crash too

**Comment by Lumpazius** [comment]
Getting the same crash report on version 2.1.10.3 for Minecraft 1.16.5.
